### ISSUE TITLE
Update dependency for react v15

### ISSUE THREAD

**Issue by onedr0p** [kadirahq/react-mounter#11]
`npm WARN react-mounter@1.1.0 requires a peer of react@0.14.x but none was installed.`
`npm WARN react-mounter@1.1.0 requires a peer of react-dom@0.14.x but none was installed.`

**Comment by KaurKirikall** [comment]
Can we get an ETA on the issue, please.

**Comment by arunoda** [comment]
Published with: v1.2.0

**Comment by joncursi** [comment]
Thank you @arunoda!
