### ISSUE TITLE
Any thoughts on when this might work in SSR?

### ISSUE THREAD

**Issue by marbemac** [kadirahq/react-mounter#3]
I know there's a lot of work going on over in FlowRouter, so perhaps you're waiting to finish up the SSR over there.

We are experimenting with the Mantra architecture for a small new project, and have made a couple of tiny tweaks to make it work with FlowRouter SSR. The only block remaining is react-mounter. We can't use react-layout because then we end up with two versions of react on the same page. 

I know you guys have a lot going on, just curious how react-mounter SSR support might fit into your roadmap. Thanks!

**Comment by teknologist** [comment]
+1

**Comment by SachaG** [comment]
Just ran into the same issue, I'd be curious to know about SSR support as well :)

**Comment by arunoda** [comment]
Will work on this soon.
Hopefully on Monday with the FlowRouter SSR first beta.

**Comment by TeemoWan** [comment]
meteor 1.3-beta.11,  the same issue.

**Comment by TeemoWan** [comment]
update react-mounter@1.1.0, Ok

**Comment by arunoda** [comment]
Now react-mounter is SSR supported. Hope we can close it :)

**Comment by arunoda** [comment]
Here's a sample app: https://github.com/kadira-samples/meteor-data-and-react

**Comment by enricofoschi** [comment]
Do they sell @arunoda's little statues I can put on my desk :)?

**Comment by payner35** [comment]
+1 for @arunoda desktop ticker.. ;)
