### ISSUE TITLE
Conflicting directions for routes.js location?

### ISSUE THREAD

**Issue by paulmolluzzo** [kadirahq/react-mounter#4]
While testing this out with Meteor v1.3-beta-6 and updating an app that is using Flow Router I realized that Flow Router suggests to put routes in `lib/routes.js` while React Mounter suggests putting it in `client/routes.js`. The difference is not negligable: If you keep it in `lib` there's an error from `domready` that `document is not defined`.

Not sure what to do exactly, but the two ought to be reconciled somehow. Maybe just make a note in this repo (or Flow Router) to look for that difference and choose accordingly.

**Comment by arunoda** [comment]
This is because react-mounter is client only for now. We'll support server side soon.

**Comment by paulmolluzzo** [comment]
👍

**Comment by arunoda** [comment]
Closing this and tracking via #3
