### ISSUE TITLE
Can't mount component that requires `this.props.children`

### ISSUE THREAD

**Issue by nightire** [kadirahq/react-mounter#8]
I'm using `react-intl` (provided by [Yahoo FormatJS](https://github.com/yahoo/react-intl)), it has a `<IntlProvider />` that needs me to mount at the top. But unfortunately this component requires `this.props.children` which I believe not suited for react-mounter's underlying mechanism.

This is how I write the codes:

``` javascript
FlowRouter.route('/', {
  name: 'home',
  action() {
    mounter(IntlProvider, {
      locale: navigator.language,
      content: () => (<StaticLayout content={() => (<PostList />)} />,)
    });
  },
});
```

will gives me warnings like this:

![image](https://cloud.githubusercontent.com/assets/1104018/13246995/f3d9871a-da51-11e5-917f-f3f22af60b76.png)

I'm not sure this is the right place to report, but I wish to get some suggestions from you, thanks in advance.

**Comment by arunoda** [comment]
You first need to create a layout class and `IntlProvider` inside that. Like this:

``` js
const Layout = ({lang, content}) => (
  <div>
    <IntlProvider lang={lang}>
      {content();}
    </IntlProvider>
  </div>
);
```

Then mount it like this:

``` js
mounter(Layout, {
  lang: 'fr',
  content: () => (<div></div>)
});
```

**Comment by nightire** [comment]
@arunoda Yes, I'm doing it right now, so the former thoughts is totally nonsense. Thank you very much!
